classDiagram
    class Bombilla{

        - nombre: string
        - numero_serie: string
        - encendida: Bool
        + enciende(): Bool
        + apaga(): Bool
        + estado(): String
        + __str__(): String

    }
